apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: <User>
  POSTGRES_PASSWORD: <Password>
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: <User>
  POSTGRES_NON_ROOT_PASSWORD: <Password>